image: Ubuntu1804
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true
services:
- docker

environment:
  nuget_api_key:
    secure: uLbsU9zHQNqoFLVXzPqk5QyoKVXu/vj6LIZEkCjqm5h+MPXR/2bQG0p8bjnnE0Oz
branches:
  only:
    - master

install:

build: off

build_script:
  - docker build -t base64urlcode -f Dockerfile.Base64UrlCore .
  - docker run -i --rm -v ${APPVEYOR_BUILD_FOLDER}/Base64UrlCore/pack:/app/pack base64urlcode
  - docker build -t base64urls -f Dockerfile.base64urls .
  - docker run -i --rm -v ${APPVEYOR_BUILD_FOLDER}/base64urls/pack:/app/pack base64urls

test_script:
  - dotnet restore src/Base64UrlCore.sln
  - dotnet test src/Base64UrlCore.Tests/Base64UrlCore.Tests.csproj

# deploy_script:
#   - if [ ${APPVEYOR_REPO_TAG} = "true" ]; then dotnet nuget push ${APPVEYOR_BUILD_FOLDER}/pack/*.nupkg -k ${nuget_api_key} -s https://api.nuget.org/v3/index.json -ss https://nuget.smbsrc.net ; fi
