version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
      BUILD_CONFIG: Release
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include=[Base64UrlCore.*]*
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: ./codecov -f ./tests/Base64UrlCore.Tests/coverage.opencover.xml
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: deploy when exists tag
          command: |
            if [ "${CIRCLE_TAG-undefined}" != "undefined" ]; then
              dotnet build -c Release -p:Version=${CIRCLE_TAG}
              dotnet test -c Release --no-build
              dotnet pack ./src/Base64UrlCore/Base64UrlCore.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
              dotnet pack ./src/base64urls/base64urls.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
              dotnet nuget push ./src/Base64UrlCore/bin/Release/Base64UrlCore.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
              dotnet nuget push ./src/base64urls/bin/Release/base64urls.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
            else
              echo tag not exists
            fi
      - store_artifacts:
          path: ./src/Base64UrlCore/bin/Release
          destination: ./Base64UrlCore/
      - store_artifacts:
          path: ./src/base64urls/bin/Release
          destination: ./base64urls/
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^[0-9](\.[0-9]){2}$/
            branches:
              only: master
