version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/Base64UrlCore/Base64UrlCore.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./globaltool/base64urls/base64urls.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/Base64UrlCore/bin/Release
          destination: ./Base64UrlCore/
      - store_artifacts:
          path: ./globaltool/base64urls/bin/Release
          destination: ./base64urls/
      - run: dotnet nuget push ./src/Base64UrlCore/bin/Release/Base64UrlCore.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      - run: dotnet nuget push ./globaltool/base64urls/bin/Release/base64urls.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/